### ISSUE TITLE
node_modules not deployed with code

### ISSUE THREAD

**Issue by darbio** [architect/deploy#105]
**Describe the issue**
When I deploy my code to AWS the node_modules folder only contains one package, `@architect/shared` and no references to any other installed node packages.

**Expected behavior**
node_modules should contain all references packages.

**Screenshots**
https://imgur.com/a/r0Zt2TN

**Comment by darbio** [comment]
(my functions work in sandbox)

**Comment by brianleroux** [comment]
hi there! you need to manually add package.json to the functions where you have deps you want. eg.

```bash
cd src/http/get-index
npm init -f
npm i @architect/functions
```

from there sandbox and deploy will both call into https://arc.codes/reference/cli/hydrate and do what you'd expect. this is a deliberate design decision. it means you have 100% of exactly the payload you want to each lambda. other systems force you into either single file bundles or (worse) fat functions which we consider antipatterns.

**Comment by brianleroux** [comment]
(if this isn't clear feel free to comment or reopen; always happy to help.)

**Comment by darbio** [comment]
Thanks. This makes sense. It might be worth updating the docs to make this clearer - maybe I missed it but I spent a few hours trying to get this working.
