### ISSUE TITLE
staging env package sets NODE_ENV env var to 'production'

### ISSUE THREAD

**Issue by filmaj** [architect/deploy#14]
Originally filed in architect/deploy#7

See https://github.com/architect/package/blob/master/src/visitors/get-lambda-env.js#L11-L12

When I run `arc deploy`, we deploy to staging initially. However, [this package code](https://github.com/architect/package/blob/master/src/visitors/get-lambda-env.js#L11-L12) always sets node_env var on lambdas to 'production'. This yields the following error for me when issuing requests against my 'sign up for an account' lambda route on the staging deployment of my app:

```User: arn:aws:sts::417817716689:assumed-role/ArctonicStaging-Role-1DTGWI2L7URY8/ArctonicStaging-PostApiSignup-3CRNEFY4IAPR is not authorized to perform: dynamodb:GetItem on resource: arn:aws:dynamodb:us-west-2:417817716689:table/arctonic-production-accounts```

Since the node_env is set to production, the `@architect/data` module is trying to issue requests against the production table, which the Staging role has no access to (and that's good!). However, package probably needs to conditionally set the node_env var based on whether we are packaging for staging or for production.

FYI @brianleroux

**Comment by brianleroux** [comment]
fixed in fixed in `+ @architect/deploy@1.0.19` and should be in the cli shortly
