### ISSUE TITLE
improve sam deploy output

### ISSUE THREAD

**Issue by filmaj** [architect/deploy#3]
what is happening here? could we describe this better, maybe?

```
sam package
         --template-file sam.json
  --output-template-file sam.yaml
             --s3-bucket arctonic
Uploading to 62284d099bd43f7b8e0d749076d00221  160491 / 160491.0  (100.00%)
Uploading to 2ea59ac0e34cf21fa02693e28e76e16a  262144 / 6080551.0  (4.31%)
Uploading to 2ea59ac0e34cf21fa02693e28e76e16a  524288 / 6080551.0  (8.62%)
Uploading to 2ea59ac0e34cf21fa02693e28e76e16a  786432 / 6080551.0  (12.93%)
Uploading to 2ea59ac0e34cf21fa02693e28e76e16a  1048576 / 6080551.0  (17.24%)
Uploading to 2ea59ac0e34cf21fa02693e28e76e16a  1310720 / 6080551.0  (21.56%)
Uploading to 2ea59ac0e34cf21fa02693e28e76e16a  1572864 / 6080551.0  (25.87%)
Uploading to 2ea59ac0e34cf21fa02693e28e76e16a  1835008 / 6080551.0  (30.18%)
Uploading to 2ea59ac0e34cf21fa02693e28e76e16a  2097152 / 6080551.0  (34.49%)
```

What is that sha-like thing we are uploading to? I'm gonna guess functions? And is the progress on the right displaying how much has been uploaded  / how much is left to upload?

**Comment by brianleroux** [comment]
This part of the process zips the local code and uploads to the S3 bucket defined under `@aws` for deployment by Cloudformation. Think this is because CFN was traditionally used to only describe resources and code deployment was a seperate process but Lambda blurring those lines.

**Comment by ryanblock** [comment]
I think this has been resolved (and improved quite a bit) since July, but please reopen if there's anything in specific we should be doing!
